### ISSUE TITLE
Facing issue while sharding

### ISSUE THREAD

**Issue by hydraindia** [DevYukine/Kurasuta#345]
`[2020-02-19 08:08:08] [CLUSTER:0] Cluster 0 spawned!
(node:3553) UnhandledPromiseRejectionWarning: TypeError: BaseManager is not a constructor`

**Comment by hydraindia** [comment]
Sharding Manager Code
`const { ShardingManager } = require("kurasuta");
const { Colors, KlasaConsole } = require("klasa");
const { join } = require('path');

const { clientConfig, colorBase } = require("./libs/config");
const RED = require("./redClient");

require("./libs/prototypes");

const shardingManager = new ShardingManager(join(__dirname, 'redCluster'), {
    client: RED,
    clientOptions: clientConfig,
    development: true,
    clusterCount: 2,
    shardCount: 4
});

const console = new KlasaConsole({
    useColor: true,
    utc: true,
    colors: {
        log: clientConfig.console.colors.startup
    }
});

shardingManager.on('error', message => {
    console.error(message);
});

shardingManager.on("spawn", cluster => {
    console.log(`${new Colors(colorBase.shard).format(`[CLUSTER:${cluster.id}]`)} Cluster ${cluster.id} spawned!`);
});

shardingManager.on('shardReady', shardID => {
    console.log(`${new Colors(colorBase.shard).format(`[${shardID}]`)} Shard ${shardID} is ready!`);
});

shardingManager.on("ready", cluster => {
    console.log(`${new Colors(colorBase.shard).format(`[CLUSTER:${cluster.id}]`)} Cluster ${cluster.id} is ready!`);
});

shardingManager.spawn();
`

**Comment by hydraindia** [comment]
Sharding Manager Code
https://hastebin.com/uqemizahud.js
Cluster Code
https://hastebin.com/iwihebukuj.js

**Comment by hydraindia** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/40756526/74817186-83982080-5322-11ea-9290-681eaae97c06.jpg)

**Comment by hydraindia** [comment]
[2020-02-19 09:05:44] [CLUSTER:0] Cluster 0 spawned!
(node:13729) UnhandledPromiseRejectionWarning: TypeError: BaseManager is not a constructor
    at RedClient.[KlasaPlugin] (/rbd/pnpm-volume/6983ab0a-7196-48c4-9b62-a1df58911c98/node_modules/.github.com/dirigeants/klasa-dashboard-hooks/80af6f6137ddeaf248f484303b652687c906ec5e/node_modules/klasa-dashboard-hooks/src/lib/Client.js:76:25)
    at new KlasaClient (/rbd/pnpm-volume/6983ab0a-7196-48c4-9b62-a1df58911c98/node_modules/.github.com/dirigeants/klasa/aee79a51a6e845b6678e96fdd1a7cc1e27fda435/node_modules/klasa/src/lib/Client.js:327:40)
at new RedClient (/app/redClient.js:13:9)
    at new BaseCluster (/rbd/pnpm-volume/6983ab0a-7196-48c4-9b62-a1df58911c98/node_modules/.registry.npmjs.org/kurasuta/1.1.6/node_modules/kurasuta/dist/Cluster/BaseCluster.js:22:23)
at new module.exports (/app/redCluster.js:6:18)
    at Object.startCluster (/rbd/pnpm-volume/6983ab0a-7196-48c4-9b62-a1df58911c98/node_modules/.registry.npmjs.org/kurasuta/1.1.6/node_modules/kurasuta/dist/Util/Util.js:85:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:13729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DevYukine** [comment]
This is related to a breaking change of d.js and Klasa-Dashboard Hooks doesn't support that commit yet.
