### ISSUE TITLE
Unsupported type 'function'.

### ISSUE THREAD

**Issue by Firat20026** [DevYukine/Kurasuta#357]
When I try using broadcastEval with functions which makes promises, it throws "unsupported type function" error. As an example when I evaluate "this.client.shard.broadcastEval("this.guilds.cache.get('someid')")` my bot doesn't give me the results. I'm new with this module so I don't know if there is another way that I should use. I looked into the source codes and found fetchGuild function but it seems like it works for just info but that function doesn't give with guild structure and functions doesn't work. 

Here is the full error: 

`Error: Unsupported type 'function'.
    at Serializer.handleUnsupported (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:60:15)
    at Serializer.parse (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:41:34)
    at Serializer.parseValueObjectLiteral (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:186:18)
    at Serializer.parseObject (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:134:49)
    at Serializer.parse (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:38:67)
    at Serializer.parseValueObjectLiteral (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:186:18)
    at Serializer.parseObject (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:134:49)
    at Serializer.parse (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:38:67)
    at Serializer.parseValueObjectLiteral (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:186:18)
    at Serializer.parseObject (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:134:49)
    at Serializer.parse (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:38:67)
    at Serializer.process (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\lib\Serializer.js:25:14)
    at Object.serialize (C:\Users\Administrator\Desktop\husnu\node_modules\binarytf\dist\index.js:6:61)
    at NodeMessage.reply (C:\Users\Administrator\Desktop\husnu\node_modules\veza\dist\lib\Structures\NodeMessage.js:28:87)
    at ClusterIPC._message (C:\Users\Administrator\Desktop\husnu\node_modules\kurasuta\dist\IPC\ClusterIPC.js:48:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'Error'
}`

Versions that I'm using if that helps:
discord.js => 12.0.2
klasa => v1.0.0-alpha
kurasuta => 2.0.0
veza => 1.1.0
binarytf => 2.0.0

**Comment by DevYukine** [comment]
You sadly can't fetch a complete structure through broadcastEval, instead find the Cluster you need and then evaluate the code on that cluster (use an if statement to check if a certain guild is present on the cluster).

fetching a complete guild strucutre is not possible since it has circular references to entities (members, channels, voiceStates etc.) and there is no way to send that form one process to another in nodejs.

If you have any further questions you can find me here https://discord.gg/5HjPTj
