### ISSUE TITLE
Unhandled Rejection: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by Vexyr** [DevYukine/Kurasuta#372]
Sometimes it throws this error.
```js
(node:16383) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at NodeMessage.reply (/root/bot/node_modules/veza/dist/lib/Structures/NodeMessage.js:28:32)
    at MasterIPC._broadcast (/root/bot/node_modules/kurasuta/dist/IPC/MasterIPC.js:45:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

What is it caused by?

**Comment by DevYukine** [comment]
This looks like an issue with the underlying IPC library `Veza`, i will try to look into that.
