### ISSUE TITLE
Clutsters failed to spawn

### ISSUE THREAD

**Issue by inhydrox** [DevYukine/Kurasuta#388]
Version: Latest

```js
require('events').EventEmitter.defaultMaxListeners = 0;

const { ShardingManager } = require("kurasuta");
const config = require('./config');
const Client = require('./structures/Client.js');

const sharder = new ShardingManager(__dirname + "/index.js", {
    token: config.token,
    client: Client,
    respawn: true, 
    retry: true,
    ipcSocket: 9999,
    guildsPerShard: 500,
    timeout: 45000
})

sharder.spawn();
```

Error:
```
[Kurasuta] [Debug] Using recommend shard count of 2 shards with 500 guilds per shard
[Kurasuta] [Debug] Starting 2 Shards in 3 Clusters!
[Kurasuta] [Debug] Worker spawned with id 1
[Kurasuta] [Debug] Cluster 0 failed to start
Error: Cluster 0 failed to start
    at ShardingManager.spawn (/rbd/pnpm-volume/38d948f2-5402-4465-ac06-b48a224c1c34/node_modules/.registry.npmjs.org/kurasuta/2.2.0/node_modules/kurasuta/dist/Sharding/ShardingManager.js:84:64)
[Kurasuta] [Debug] Requeuing Cluster 0 to be spawned
[Kurasuta] [Debug] Worker spawned with id 2
[Kurasuta] [Debug] [IPC] Client Connected: Cluster 0
[Monday November 2nd 12:40 PM] [MongoDB] Connection established
[Kurasuta] [Debug] Cluster 1 failed to start
[Kurasuta] [Debug] Requeuing Cluster 1 to be spawned
[Kurasuta] [Debug] Respawning Cluster 0
[Kurasuta] [Debug] Killing Cluster 0
Error: Cluster 1 failed to start
    at ShardingManager.spawn (/rbd/pnpm-volume/38d948f2-5402-4465-ac06-b48a224c1c34/node_modules/.registry.npmjs.org/kurasuta/2.2.0/node_modules/kurasuta/dist/Sharding/ShardingManager.js:84:64)
[Kurasuta] [Debug] Worker spawned with id 3
[Kurasuta] [Debug] [IPC] Client Disconnected: Cluster 0
[Kurasuta] [Debug] [IPC] Client Connected: Cluster 1
[Kurasuta] [Debug] Cluster 0 failed, requeuing...
[Kurasuta] [Debug] Respawning Cluster 1
[Kurasuta] [Debug] Killing Cluster 1
[Kurasuta] [Debug] Worker spawned with id 4
[Monday November 2nd 12:40 PM] [MongoDB] Connection established
[Kurasuta] [Debug] [IPC] Client Disconnected: Cluster 1
[Kurasuta] [Debug] Cluster 1 failed, requeuing...
[Kurasuta] [Debug] 2 Clusters still failed, retry...
[Kurasuta] [Debug] Respawning Cluster 0
[Kurasuta] [Debug] Killing Cluster 0
[Kurasuta] [Debug] Worker spawned with id 5
[Kurasuta] [Debug] Cluster 0 failed, requeuing...
[Kurasuta] [Debug] Respawning Cluster 1
[Kurasuta] [Debug] Killing Cluster 1
[Kurasuta] [Debug] Worker spawned with id 6
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[Kurasuta] [Debug] [IPC] Client Disconnected: null
```

**Comment by inhydrox** [comment]
I don't know the error got fixed somehow
