### ISSUE TITLE
error

### ISSUE THREAD

**Issue by inhydrox** [DevYukine/Kurasuta#400]
```
4|mt-trial  | [Kurasuta] [Debug] Using recommend shard count of 3 shards with 1000 guilds per shard
4|mt-trial  | [Kurasuta] [Debug] Starting 3 Shards in 2 Clusters!
4|mt-trial  | [Kurasuta] [Debug] Worker spawned with id 1
4|mt-trial  | [Kurasuta] [Debug] [IPC] Client Connected: Cluster 0
4|mt-trial  | [Saturday February 13th 8:42 AM] [MongoDB] Database has been disconnected!
4|mt-trial  | [Kurasuta] [Debug] [IPC] Shard 0 disconnected!
4|mt-trial  | [Kurasuta] [Shard] Shard [object Object] disconnected.
4|mt-trial  | Error [SHARDING_REQUIRED]: This session would have handled too many guilds - Sharding is required.
4|mt-trial  |     at WebSocketManager.createShards (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
4|mt-trial  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
4|mt-trial  |     at async TuneyClient.login (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/Client.js:223:7) {
4|mt-trial  |   [Symbol(code)]: 'SHARDING_REQUIRED'
4|mt-trial  | }
4|mt-trial  | Error [SHARDING_REQUIRED]: This session would have handled too many guilds - Sharding is required.
4|mt-trial  |     at WebSocketManager.createShards (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
4|mt-trial  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
4|mt-trial  |     at async TuneyClient.login (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/Client.js:223:7)
```

Why am I getting this?

**Comment by inhydrox** [comment]
My code

```js
require('events').EventEmitter.defaultMaxListeners = 0;

const { ShardingManager } = require("kurasuta");
const config = require('./config');
const Client = require('./structures/Client.js');

const sharder = new ShardingManager(__dirname + "/app.js", {
  token: config.token,
  client: Client,
  respawn: true,
  retry: true,
  ipcSocket: 9999,
  guildsPerShard: 800,
  //    timeout: 45000,
 // clusterCount: 1
});

sharder.spawn();
```

**Comment by inhydrox** [comment]
My bot is on 3K servers

**Comment by inhydrox** [comment]
```js
7|mt-only  | Preparing to connect to the gateway...
7|mt-only  | [WS => Manager] Fetched Gateway Information
7|mt-only  |     URL: wss://gateway.discord.gg
7|mt-only  |     Recommended Shards: 3
7|mt-only  | [WS => Manager] Session Limit Information
7|mt-only  |     Total: 1000
7|mt-only  |     Remaining: 245
7|mt-only  | [WS => Manager] Spawning shards: 0, 1
7|mt-only  | [WS => Shard 0] [CONNECT]
7|mt-only  |     Gateway    : wss://gateway.discord.gg/
7|mt-only  |     Version    : 6
7|mt-only  |     Encoding   : json
7|mt-only  |     Compression: none
7|mt-only  | [WS => Shard 0] Setting a HELLO timeout for 20s.
7|mt-only  | [WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 74ms
7|mt-only  | [WS => Shard 0] Clearing the HELLO timeout.
7|mt-only  | [WS => Shard 0] Setting a heartbeat interval for 41250ms.
7|mt-only  | [WS => Shard 0] [IDENTIFY] Shard 0/4
7|mt-only  | [WS => Shard 0] [CLOSE]
7|mt-only  |     Event Code: 4011
7|mt-only  |     Clean     : true
7|mt-only  |     Reason    : Sharding required.
7|mt-only  | [WS => Shard 0] Clearing the heartbeat interval.
7|mt-only  | [Kurasuta] [Debug] [IPC] Shard 0 disconnected!
7|mt-only  | [Kurasuta] [Shard] Shard [object Object] disconnected.
7|mt-only  | [WS => Shard 0] SHARDING_REQUIRED
7|mt-only  | [WS => Manager] Manager was destroyed. Called by:
7|mt-only  | Error: MANAGER_DESTROYED
7|mt-only  |     at WebSocketManager.destroy (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/websocket/WebSocketManager.js:333:54)
7|mt-only  |     at TuneyClient.destroy (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/Client.js:237:13)
7|mt-only  |     at TuneyClient.login (/home/utkarsh/mt-trial/node_modules/discord.js/src/client/Client.js:226:12)
7|mt-only  |     at processTicksAndRejections (internal/process/task_queues.js:89:5)
7|mt-only  | [WS => Shard 0] WS State: CLOSED
``` 
debug

**Comment by DevYukine** [comment]
This was related to a Discord API Issue which happened yesterday, not related to Kurasuta
