### ISSUE TITLE
ClusterClass is not a constructor

### ISSUE THREAD

**Issue by ItsYourBoyNoah** [DevYukine/Kurasuta#413]
Hello, I am using the Kurasuta sharder with the correct options and everything but when I start my file I get this:

[2021-06-09 19:51:06] [ERROR] TypeError: ClusterClass is not a constructor
    at Object.startCluster (C:\Users\User\Desktop\Role Manager\node_modules\kurasuta\dist\Util\Util.js: 100:21)

so cluster and shards fail to load, why?

**Comment by hydrox19** [comment]
Yeah same issue

**Comment by hydrox19** [comment]
```js
[Kurasuta] [Debug] Using recommend shard count of 1 shards with 1000 guilds per shard
[Kurasuta] [Debug] Starting 1 Shards in 3 Clusters!
[Kurasuta] [Debug] Worker spawned with id 1
TypeError: ClusterClass is not a constructor
    at Object.startCluster (/rbd/pnpm-volume/65ee10ce-5db1-48e3-8f0f-90f9ae156c7e/node_modules/kurasuta/dist/Util/Util.js:100:21)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:54:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
    at internal/main/run_main_module.js:17:11
[Process 14960] [[Shard] [0]] Shard Ready
[Process 14960] [Live Music] Ready with 1 servers!
[Kurasuta] [Debug] Cluster 0 failed to start
(node:14941) UnhandledPromiseRejectionWarning: Error: Cluster 0 failed to start
    at ShardingManager.spawn (/rbd/pnpm-volume/65ee10ce-5db1-48e3-8f0f-90f9ae156c7e/node_modules/kurasuta/dist/Sharding/ShardingManager.js:85:64)
(node:14941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by hydrox19** [comment]
I fixed the error I made a dumb mistake.

**Comment by hydrox19** [comment]
```js
const { BaseCluster } = require('kurasuta');

module.exports = class extends BaseCluster {
	launch() {
		this.client.login("YOUR BOT TOKEN");
	}
};
```
You are missing this

**Comment by ItsYourBoyNoah** [comment]
> ```js
> const { BaseCluster } = require('kurasuta');
> 
> module.exports = class extends BaseCluster {
> 	launch() {
> 		this.client.login("YOUR BOT TOKEN");
> 	}
> };
> ```
> You are missing this

Can you show me the file you use for sharding? I want to compare it to mine to see what mistakes I have

**Comment by ItsYourBoyNoah** [comment]
```js
const { MessageEmbed } = require('discord.js');

const Logger = require('./utils/Logger');
const WebhookManager = require('./managers/WebhookManager');
const config = require('./config');
const variables = require('./utils/variables');

const { ShardingManager } = require('kurasuta');
const { join } = require('path');
const sharder = new ShardingManager(join(__dirname, 'index'), {
    clientOptions: variables.sharding.clientOptions,
    clusterCount: variables.sharding.clusterCount,
    shardCount: variables.sharding.shardCount,
    development: variables.sharding.development,
    guildsPerShard: variables.sharding.guildsPerShard,
    respawn: variables.sharding.respawn,
    token: config.token,
    retry: variables.sharding.retry
});

sharder.on('debug', (message) => {
    Logger.debug(message);
});

sharder.on('message', (message) => {
    Logger.info(message);
});

sharder.on('ready', (cluster) => {
    Logger.info(`Cluster ${cluster.id} is ready`);
    const e = new MessageEmbed()
    .setColor(variables.colours.green)
    .setDescription(`Cluster **${cluster.id}** is ready.`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.on('spawn', (cluster) => {
    Logger.info(`Cluster ${cluster.id} has spawned`);
    const e = new MessageEmbed()
    .setColor(variables.colours.green)
    .setDescription(`Cluster **${cluster.id}** has spawned.`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.on('shardReady', (shardID) => {
    Logger.info(`Shard ${shardID} is ready`);
    const e = new MessageEmbed()
    .setColor(variables.colours.green)
    .setDescription(`Shard **${shardID}** is ready.`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.on('shardReconnect', (shardID) => {
    Logger.info(`Shard ${shardID} has reconnected`);
    const e = new MessageEmbed()
    .setColor(variables.colours.yellow)
    .setDescription(`Shard **${shardID}** has reconnected.`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.on('shardResume', (replayed, shardID) => {
    Logger.info(`Shard ${shardID} has resumed after ${replayed} reconnect attempts`);
    const e = new MessageEmbed()
    .setColor(variables.colours.green)
    .setDescription(`Shard **${shardID}** has resumed after **${replayed}** reconnect attempts.`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.on('shardDisconnect', (closeEvent, shardID) => {
    Logger.info(`Shard ${shardID} has disconnected (${closeEvent})`);
    const e = new MessageEmbed()
    .setColor(variables.colours.red)
    .setDescription(`Shard **${shardID}** has disconnected (${closeEvent}).`)
    .setTimestamp()
    WebhookManager.botlogs.send({ embeds: [e] });
});

sharder.spawn();```

This is my code, what am I missing?

**Comment by ItsYourBoyNoah** [comment]
> 
> 
> ```js
> const { BaseCluster } = require('kurasuta');
> 
> module.exports = class extends BaseCluster {
> 	launch() {
> 		this.client.login("YOUR BOT TOKEN");
> 	}
> };
> ```
> 
> You are missing this

So update, I added to my main code this line you said like this:

```js
const { Client, Collection } = require('discord.js');
const client = new Client({ fetchAllMembers: true, partials: ['CHANNEL', 'MESSAGE', 'REACTION'], messageCacheMaxSize: 400, messageCacheLifetime: 120, messageSweepInterval: 60 });

const { BaseCluster } = require('kurasuta');

module.exports = class extends BaseCluster {
	launch() {


client.config = require('./config');
client.logger = require('./utils/Logger');
client.webhooks = require('./managers/WebhookManager');

client.commands = new Collection();
client.aliases = new Collection();

client.on('messageUpdate', (oldMsg, message) => {
    if(oldMsg.content != message.content) client.emit('message', message)
  })

require('./utils/CommandLoader')(client);
require('./utils/EventLoader')(client);
require('./managers/EmbedManager')(client);

process.on('unhandledRejection', (error) => {
    client.logger.error(error.stack);
});

process.on('uncaughtException', (error) => {
    client.logger.error(error.stack);
});

process.on('UnhandledPromiseRejectionWarning', (error) => {
    client.logger.error(error.stack);
});

client.login(client.config.token);

process.setMaxListeners(0);
client.setMaxListeners(0);
}
};```

it still has the same error

**Comment by hydrox19** [comment]
before `client.config` define client

```js
const client = this.client;
```

**Comment by ItsYourBoyNoah** [comment]
> 
> 
> before `client.config` define client
> 
> ```js
> const client = this.client;
> ```

No, my client is used like this I dont require this.

**Comment by hydrox19** [comment]
> > before `client.config` define client
> > ```js
> > const client = this.client;
> > ```
> 
> No, my client is used like this I dont require this.

```js
const { Collection } = require('discord.js');
const { BaseCluster } = require('kurasuta');

module.exports = class extends BaseCluster {
	launch() {


client.config = require('./config');
client.logger = require('./utils/Logger');
client.webhooks = require('./managers/WebhookManager');

client.commands = new Collection();
client.aliases = new Collection();

client.on('messageUpdate', (oldMsg, message) => {
    if(oldMsg.content != message.content) client.emit('message', message)
  })

require('./utils/CommandLoader')(client);
require('./utils/EventLoader')(client);
require('./managers/EmbedManager')(client);

process.on('unhandledRejection', (error) => {
    client.logger.error(error.stack);
});

process.on('uncaughtException', (error) => {
    client.logger.error(error.stack);
});

process.on('UnhandledPromiseRejectionWarning', (error) => {
    client.logger.error(error.stack);
});

client.login(client.config.token);

process.setMaxListeners(0);
client.setMaxListeners(0);
}
};
```
there you go fixed it for you

**Comment by ItsYourBoyNoah** [comment]
> > > before `client.config` define client
> > > ```js
> > > const client = this.client;
> > > ```
> > 
> > No, my client is used like this I dont require this.
> 
> ```js
> const { Collection } = require('discord.js');
> const { BaseCluster } = require('kurasuta');
> 
> module.exports = class extends BaseCluster {
> 	launch() {
> 
> 
> client.config = require('./config');
> client.logger = require('./utils/Logger');
> client.webhooks = require('./managers/WebhookManager');
> 
> client.commands = new Collection();
> client.aliases = new Collection();
> 
> client.on('messageUpdate', (oldMsg, message) => {
>     if(oldMsg.content != message.content) client.emit('message', message)
>   })
> 
> require('./utils/CommandLoader')(client);
> require('./utils/EventLoader')(client);
> require('./managers/EmbedManager')(client);
> 
> process.on('unhandledRejection', (error) => {
>     client.logger.error(error.stack);
> });
> 
> process.on('uncaughtException', (error) => {
>     client.logger.error(error.stack);
> });
> 
> process.on('UnhandledPromiseRejectionWarning', (error) => {
>     client.logger.error(error.stack);
> });
> 
> client.login(client.config.token);
> 
> process.setMaxListeners(0);
> client.setMaxListeners(0);
> }
> };
> ```
> there you go fixed it for you

I think I had it like that but it errored again, I'll try this and let you know if any errors occur

**Comment by ItsYourBoyNoah** [comment]
Nope I still get this:

```(node:36) UnhandledPromiseRejectionWarning: TypeError: ClusterClass is not a constructor
    at Object.startCluster (/home/container/node_modules/kurasuta/dist/Util/Util.js:100:21)```

**Comment by DevYukine** [comment]
This i not a Kurasuta issue but an end user issue on your side, Kurasuta expects you to pass the path of a cluster file which extends `BaseCluster` to `ShardingManager` constructor as first parameter, in your case the file you pass doesn't extend BaseCluster, its not even a class
