### ISSUE TITLE
Don't know a name, but priority medium-high

### ISSUE THREAD

**Issue by hydrox19** [DevYukine/Kurasuta#424]
```js
Error: Cannot send a message to a missing socket.
    at ClientSocket.send (/root/tune/node_modules/veza/dist/lib/Structures/Base/SocketHandler.js:34:35)
    at ShardClientUtil.send (/root/tune/node_modules/kurasuta/dist/Sharding/ShardClientUtil.js:57:36)
    at TuneClient.<anonymous> (/root/tune/node_modules/kurasuta/dist/Cluster/BaseCluster.js:46:67)
    at TuneClient.emit (events.js:375:28)
    at Object.module.exports [as RESUMED] (/root/tune/node_modules/discord.js/src/client/websocket/handlers/RESUMED.js:13:10)
    at WebSocketManager.handlePacket (/root/tune/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/root/tune/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/root/tune/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/root/tune/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (/root/tune/node_modules/ws/lib/websocket.js:970:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (/root/tune/node_modules/ws/lib/receiver.js:502:14)
    at Receiver.getData (/root/tune/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/root/tune/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/root/tune/node_modules/ws/lib/receiver.js:78:10)
``` this error emits so many times like when I searched the log file (output of 3 days) I have find around 350+ matches and my bot restarts like so much haven't been able to find any cause and I suspect this could be the case

**Comment by hydrox19** [comment]
and there is one more error because of that one of my friend bot's I created is restarting many times```js
MessageError: Failed to process message during connection, calling disconnect: Unknown type received: 67 [UnknownType]
    at Object.makeError (/root/chillbot-alpha/node_modules/veza/dist/lib/Structures/MessageError.js:33:16)
    at ServerSocket._onData (/root/chillbot-alpha/node_modules/veza/dist/lib/ServerSocket.js:93:62)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  kind: 'UnknownType'
}
```

**Comment by DevYukine** [comment]
This seems to be another weird case of `Veza` bugs which are sadly there, i can't really tell you much about it but i would suggest that you check your internal network connection being correctly setup and stable
