### ISSUE TITLE
env.CLUSTER_SHARDS is undefined

### ISSUE THREAD

**Issue by TheOnlyArtz** [DevYukine/Kurasuta#452]
`index.ts`

```ts
import { Intents, Options } from "discord.js";
import { join } from "path/posix";
import Rick from "./Models/Rick";

const { ShardingManager } = require("kurasuta");
const sharder = new ShardingManager(join(__dirname, "shard"), {
  clusterCount: 1,
  guildsPerShard: 1200,
  client: Rick,
  clientOptions: {
    intents: [
      Intents.FLAGS.GUILDS,
      Intents.FLAGS.GUILD_INTEGRATIONS,
      Intents.FLAGS.GUILD_MEMBERS,
      Intents.FLAGS.GUILD_MESSAGES,
      Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
      Intents.FLAGS.GUILD_PRESENCES,
      Intents.FLAGS.GUILD_VOICE_STATES,
      Intents.FLAGS.DIRECT_MESSAGES,
      Intents.FLAGS.DIRECT_MESSAGE_TYPING,
    ],

    makeCache: Options.cacheWithLimits({
      MessageManager: {
        maxSize: 25,
        sweepInterval: 43200,
      },
      PresenceManager: 0,
    }),
  },
});

sharder.spawn();
```

`shard.ts`
```ts
import { Intents } from 'discord.js';
import { ShardingManager } from 'kurasuta';
import { BaseCluster } from 'kurasuta';
import Rick from './Models/Rick';

export default class extends BaseCluster {
    constructor(manager: ShardingManager) {
        super(manager)
    }

	async launch() {
		await (this.client as Rick).bootstrap(this.client.token!);
	}
};
```

```
                const shards = env.CLUSTER_SHARDS!.split(',').map(Number);
                                     ^
TypeError: Cannot read property 'split' of undefined
    at new BaseCluster (H:\Rickbot\rickbot-3\node_modules\kurasuta\src\Cluster\BaseCluster.ts:14:38)
    at new default_1 (H:\Rickbot\rickbot-3\src\shard.ts:8:9)
    at Object.startCluster (H:\Rickbot\rickbot-3\node_modules\kurasuta\src\Util\Util.ts:78:1
```

Looking at #411 I've done everything the right way!

**Comment by TheOnlyArtz** [comment]
ERROR WAS SOLVED BY UPDATING NODE TO 15+

**Comment by DevYukine** [comment]
Kurasuta will always require the same version as Discord.js does, Kurasuta v3 upgraded to d.js v13 which requires node 16.6.0 atm for people reading this right now :)
