### ISSUE TITLE
Error: Unsupported type 'function'.

### ISSUE THREAD

**Issue by Tetracyl** [DevYukine/Kurasuta#460]
I'm trying to create a broadcast command which sends a message to all servers in all clusters that have a player but I'm getting the following error:

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Unsupported type 'function'.
    at Serializer.handleUnsupported (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:60:15)
    at Serializer.parse (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:41:34)
    at Serializer.parseValueObjectLiteral (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:186:18)
    at Serializer.parseObject (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:134:49)
    at Serializer.parse (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:38:67)
    at Serializer.parseValueObjectLiteral (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:186:18)
    at Serializer.parseObject (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:134:49)
    at Serializer.parse (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:38:67)
    at Serializer.parseValueObjectMap (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:197:18)
    at Serializer.parseObject (/home/seif/EarTensifier/node_modules/binarytf/dist/lib/Serializer.js:135:46)
```

Code:
```js
const players = await client.shard.broadcastEval(`this.music.players.each(p => p.textChannel.send('${message}'))`);
```

I tried looking at https://github.com/DevYukine/Kurasuta/issues/357 but don't see how this could apply in my use case since I want to send a message in all clusters and not just certain ones.

**Comment by ChandanOP** [comment]
Same that error occurred  with me
